# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.28.3"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    # cocoapods
    cocoapods(use_bundle_exec: false)
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    # sync_code_signing(type: "appstore")  # see code signing guide for more information
    # gym(scheme: "GogoroMap")
    # build_app(scheme: "GogoroMap")
    # upload_to_app_store

    # build_app(scheme: "GogoroMap",
    #           workspace: "GogoroMap.xcworkspace",
    #           include_bitcode: true)
    # increment_build_number
    # # match(type: "appstore")
    # gym(
    #   clean: true,
    #   scheme:"GogoroMap",
    #   export_method:"app-store",
    #   output_directory:"./build",
    #   archive_path:"./Archive"
    # )

    deliver(
      submit_for_review: true,
      force: true, # Skip HTMl report verification
      skip_screenshots: true,
      skip_binary_upload: true,
      automatic_release: true,
      promotional_text: {
              'zh-Hant' => "騎gogoro沒電了嗎？
              協助你紀錄旅遊行程，足跡
              這裡可以幫助你快速的找到最近的充電站
              讓你充滿能量再出發！",
              'en-US' => "Need energy for long distance travel without pollution? Go Station will help you find the battery exchange station for gogoro Have a great travel experience"
            },
     release_notes: {
        'zh-Hant' => "支援 Dark mode
        列表支援左右滑動，切換過濾站點項目(附近, 已打卡, 未打卡, 即將啟用)
        臭蟲修復
        加強電池效能
        加速電池站點狀態更新演算法
        地圖站點與過濾站點清單同步
        回應許願需求
        增進搜尋效率",
        'en-US' => "new status icon for station nearby bank
        support dark mode
        better battery performance
        new filter mode for clear where you have been
        more performance for backup flow"
      },
      # Comes from https://github.com/fastlane/fastlane/issues/5542#issuecomment-254201994
      submission_information: {
        add_id_info_limits_tracking: true,
        add_id_info_serves_ads: true,
        add_id_info_tracks_action: false,
        add_id_info_tracks_install: false,
        add_id_info_uses_idfa: true,
        content_rights_has_rights: true,
        content_rights_contains_third_party_content: true,
        export_compliance_platform: 'ios',
        export_compliance_compliance_required: false,
        export_compliance_encryption_updated: false,
        export_compliance_app_type: nil,
        export_compliance_uses_encryption: false,
        export_compliance_is_exempt: false,
        export_compliance_contains_third_party_cryptography: false,
        export_compliance_contains_proprietary_cryptography: false,
        export_compliance_available_on_french_store: false
      }
    )


    puts 'All done'
    # frameit
  end
  # You can define as many lanes as you want
end

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end



# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
